
name: Linux Build

on:
  push:
    branches: [ "api-style" ]
  pull_request:
    branches: [ "api-style" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        # Set fail-fast to false to ensure that feedback is delivered for all matrix
        # combinations. Consider changing this to true when your workflow is stable.
        fail-fast: false

        matrix:
            cmake_preset: [
              "linux-x64-gcc-debug",
              "linux-x64-clang-debug",
              "linux-x64-gcc-release",
              "linux-x64-clang-release"
            ]

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Configure Linux CMake Preset
          run: cmake --preset ${{ matrix.cmake_preset }}
          shell: bash

        - name: Build Linux CMake Preset
          run: cmake --build --preset ${{ matrix.cmake_preset }}
          shell: bash
