
name: Windows Build

on:
  push:
    branches: [ "api-style" ]
  pull_request:
    branches: [ "api-style" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
        # Set fail-fast to false to ensure that feedback is delivered for all matrix
        # combinations. Consider changing this to true when your workflow is stable.
        fail-fast: false

        matrix:
            cmake_preset: [
              "win32-x64-msvc-debug",
              "win32-x64-mingw-debug",
              "win32-x64-msvc-release",
              "win32-x64-mingw-release"
            ]

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup MSVC Environment
          uses: ilammy/msvc-dev-cmd@v1.13.0
        
        - name: Configure Windows CMake Preset
          run: cmake --preset ${{ matrix.cmake_preset }}
          shell: cmd

        - name: Build Windows CMake Preset
          run: cmake --build --preset ${{ matrix.cmake_preset }}
          shell: cmd
